// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"git.cie.com/ips/wire-provider/gin/provider"
	"github.com/ZecretBone/ips-bff/cmd/bff-api/handler"
	"github.com/ZecretBone/ips-bff/cmd/bff-api/server"
	"github.com/ZecretBone/ips-bff/internal/config"
	"github.com/ZecretBone/ips-bff/internal/di"
	"github.com/ZecretBone/ips-bff/internal/repository/grpc/dataCollectionClient"
	"github.com/ZecretBone/ips-bff/internal/repository/grpc/mapClient"
	"github.com/ZecretBone/ips-bff/internal/repository/grpc/userTrackingClient"
	"github.com/google/wire"
)

// Injectors from di.go:

func InitializeContainer() (*Container, func(), error) {
	grpcConfig := config.ProvideGRPCServiceConfig()
	service := datacollectionclient.ProvideDataCollectionGRPCClient(grpcConfig)
	dataCollectionHandler := handler.ProvideDataCollectionHandler(service)
	usertrackingclientService := usertrackingclient.ProvideUserTrackingService(grpcConfig)
	userTrackingHandler := handler.ProvideUserTrackingHandler(usertrackingclientService)
	mapgrpcclientService := mapgrpcclient.ProvideMapService(grpcConfig)
	mapHandler := handler.ProvideMapHandler(mapgrpcclientService)
	handlers := handler.Handlers{
		StatCollection: dataCollectionHandler,
		UserTracking:   userTrackingHandler,
		Map:            mapHandler,
	}
	routerCustomizer := server.ProvideGinRouterCustomizer(handlers)
	ginServer, cleanup, err := provider.ProvideGinServer(routerCustomizer)
	if err != nil {
		return nil, nil, err
	}
	container := &Container{
		server: ginServer,
	}
	return container, func() {
		cleanup()
	}, nil
}

// di.go:

var BaseBindingSet = wire.NewSet(
	ProviderSet,
	CustomizerSet, di.DatabaseSet, di.ConfigSet, di.ProviderSet,
)

var MainBindingSet = wire.NewSet(
	BaseBindingSet, provider.WireSet, wire.Struct(new(Container), "*"),
)
