// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_mapclient is a generated GoMock package.
package mock_mapclient

import (
	context "context"
	reflect "reflect"

	mapv1 "github.com/ZecretBone/ips-bff/internal/gen/proto/ips/map/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetFloorList mocks base method.
func (m *MockService) GetFloorList(ctx context.Context, body *mapv1.GetFloorListRequest) (*mapv1.GetFloorListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorList", ctx, body)
	ret0, _ := ret[0].(*mapv1.GetFloorListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorList indicates an expected call of GetFloorList.
func (mr *MockServiceMockRecorder) GetFloorList(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorList", reflect.TypeOf((*MockService)(nil).GetFloorList), ctx, body)
}

// GetFloorMapURL mocks base method.
func (m *MockService) GetFloorMapURL(ctx context.Context, body *mapv1.GetMapURLRequest) (*mapv1.GetMapURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorMapURL", ctx, body)
	ret0, _ := ret[0].(*mapv1.GetMapURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorMapURL indicates an expected call of GetFloorMapURL.
func (mr *MockServiceMockRecorder) GetFloorMapURL(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorMapURL", reflect.TypeOf((*MockService)(nil).GetFloorMapURL), ctx, body)
}
