// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_mapclient is a generated GoMock package.
package mock_mapclient

import (
	context "context"
	reflect "reflect"

	mapv1 "github.com/ZecretBone/ips-bff/internal/gen/proto/ips/map/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBuildingDetail mocks base method.
func (m *MockService) GetBuildingDetail(ctx context.Context, body *mapv1.GetBuildingInfoRequest) (*mapv1.GetBuildingInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingDetail", ctx, body)
	ret0, _ := ret[0].(*mapv1.GetBuildingInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingDetail indicates an expected call of GetBuildingDetail.
func (mr *MockServiceMockRecorder) GetBuildingDetail(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingDetail", reflect.TypeOf((*MockService)(nil).GetBuildingDetail), ctx, body)
}

// GetBuildingList mocks base method.
func (m *MockService) GetBuildingList(ctx context.Context, body *mapv1.GetBuildingListRequest) (*mapv1.GetBuildingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingList", ctx, body)
	ret0, _ := ret[0].(*mapv1.GetBuildingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingList indicates an expected call of GetBuildingList.
func (mr *MockServiceMockRecorder) GetBuildingList(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingList", reflect.TypeOf((*MockService)(nil).GetBuildingList), ctx, body)
}

// GetFloorDetail mocks base method.
func (m *MockService) GetFloorDetail(ctx context.Context, body *mapv1.GetFloorInfoRequest) (*mapv1.GetFloorInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorDetail", ctx, body)
	ret0, _ := ret[0].(*mapv1.GetFloorInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorDetail indicates an expected call of GetFloorDetail.
func (mr *MockServiceMockRecorder) GetFloorDetail(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorDetail", reflect.TypeOf((*MockService)(nil).GetFloorDetail), ctx, body)
}
